In [2]:
import numpy as np
import sys
sys.path.append("..")

from python.initialization import random_initialization, Iterative_diagonalization
from python.Zippers import *
from python.Contract import *
from python.DMRG import DMRG

In [3]:
MPS1 = [np.random.rand(1, 2, 2), np.random.rand(2, 3, 2)]
MPO = [np.random.rand(1, 2, 2, 2), np.random.rand(2, 2, 2, 2)]
MPS2 = [np.random.rand(1, 2, 2), np.random.rand(2, 3, 2) ]

MPS_MPO_MPS_env(MPS1, MPO, MPS2).shape

(3, 2, 3)

In [4]:
n_sites = 8
size = 2**n_sites

matrix_Hamiltonian = np.random.rand(size, size) + 1j * np.random.rand(size, size)

matrix_Hamiltonian = matrix_Hamiltonian + matrix_Hamiltonian.conj().T

MPO_Hamiltonian = matrix_Hamiltonian.reshape(tuple([2 for _ in range(2*n_sites)]))

MPO = Hamiltonian_to_MPO(MPO_Hamiltonian)

In [5]:
eigvals, eigvecs = EIGH(matrix_Hamiltonian)
eigvals

array([ 2.56398480e+02,  1.78859129e+01,  1.73991895e+01,  1.72617911e+01,
        1.69867124e+01,  1.66969260e+01,  1.65844502e+01,  1.63776248e+01,
        1.60336080e+01,  1.57053690e+01,  1.54781862e+01,  1.51775215e+01,
        1.49094221e+01,  1.47918273e+01,  1.47029679e+01,  1.43611500e+01,
        1.41555569e+01,  1.39443592e+01,  1.37882359e+01,  1.36879570e+01,
        1.35605997e+01,  1.33277646e+01,  1.32028324e+01,  1.29898907e+01,
        1.28426355e+01,  1.27790676e+01,  1.25254790e+01,  1.24174509e+01,
        1.22934505e+01,  1.22198808e+01,  1.20388031e+01,  1.18051149e+01,
        1.16704606e+01,  1.15208202e+01,  1.14634672e+01,  1.12578333e+01,
        1.11595071e+01,  1.11160366e+01,  1.08744261e+01,  1.07691946e+01,
        1.06149045e+01,  1.03379897e+01,  1.02933255e+01,  1.01450130e+01,
        1.00238672e+01,  9.79768797e+00,  9.74920081e+00,  9.56494446e+00,
        9.41081558e+00,  9.28487160e+00,  9.19835198e+00,  8.97255306e+00,
        8.88945433e+00,  

In [6]:
# test_Hamiltonian = MPO_to_Hamiltonian(MPO)
# np.linalg.norm(matrix_Hamiltonian - test_Hamiltonian)

In [7]:
# eigvals, eigvecs = EIGH(test_Hamiltonian)
# eigvals

In [8]:
# np.linalg.norm(test_Hamiltonian - eigvecs @ np.diag(eigvals) @ eigvecs.conj().T)

In [9]:
NKeep = 8
NSweep = 10
Krylov_bases = 5
iterative_diag = True
two_site = True
verbose = True

Hamiltonian = [
    mpo.transpose(2, 3, 0, 1) for mpo in MPO
]

In [13]:
Hamiltonian[1].shape

(2, 2, 4, 16)

In [11]:
energies, times, MPS = DMRG(
    Hamiltonian = Hamiltonian,
    NKeep = NKeep,
    NSweep = NSweep,
    Krylov_bases = Krylov_bases,
    iterative_diag = iterative_diag,
    two_site = two_site,
    verbose = verbose,
)

iter=0 | energy=-3.9442151 | time=0.0s
iter=1 | energy=-16.378091 | time=0.463s
iter=2 | energy=-16.444178 | time=1.13s
iter=3 | energy=-16.486775 | time=1.62s
iter=4 | energy=-16.581441 | time=1.99s
iter=5 | energy=-16.629807 | time=2.34s
iter=6 | energy=-16.67305 | time=2.76s
iter=7 | energy=-16.714543 | time=3.12s
iter=8 | energy=-16.74396 | time=3.56s
iter=9 | energy=-16.76229 | time=4.03s
iter=10 | energy=-16.774295 | time=4.75s


In [49]:
energies, times, MPS = DMRG(
    Hamiltonian = Hamiltonian,
    NKeep = NKeep,
    NSweep = NSweep,
    Krylov_bases = Krylov_bases,
    iterative_diag = False,
    two_site = two_site,
    verbose = verbose,
)

iter=0 | energy=-0.057025069 | time=0.0s
iter=1 | energy=-15.926392 | time=0.398s
iter=2 | energy=-16.435473 | time=0.703s
iter=3 | energy=-16.472115 | time=0.955s
iter=4 | energy=-16.458318 | time=1.2s
iter=5 | energy=-16.436612 | time=1.36s
iter=6 | energy=-16.479124 | time=1.6s
iter=7 | energy=-16.51593 | time=1.78s
iter=8 | energy=-16.529058 | time=1.95s
iter=9 | energy=-16.533532 | time=2.11s
iter=10 | energy=-16.535016 | time=2.28s


In [50]:
energies

array([ -0.05702507, -15.92639159, -16.43547339, -16.47211514,
       -16.45831824, -16.43661245, -16.47912435, -16.51592966,
       -16.52905765, -16.53353183, -16.53501636])

In [51]:
MPS_MPS_overlap(MPS, MPS)

array(1.+0.j)

In [52]:
MPS_MPO_MPS_overlap(MPS, MPO, MPS)

array(-16.53501636-8.8817842e-16j)

In [53]:
np.linalg.norm(contract_MPS(MPS))

1.0000000000000007

In [54]:
np.linalg.norm(MPS_MPO_multiplication(MPS, MPO) / MPS_MPO_MPS_overlap(MPS, MPO, MPS) - contract_MPS(MPS))

0.2648957489098576

In [55]:
two_site = False

energies, times, MPS = DMRG(
    Hamiltonian = Hamiltonian,
    NKeep = NKeep,
    NSweep = NSweep,
    Krylov_bases = Krylov_bases,
    two_site = two_site,
    verbose = verbose
)

iter=0 | energy=-4.3001611 | time=0.0s
iter=1 | energy=-15.095447 | time=0.115s
iter=2 | energy=-15.639503 | time=0.498s
iter=3 | energy=-15.974287 | time=0.848s
iter=4 | energy=-16.154388 | time=1.5s
iter=5 | energy=-16.228014 | time=1.61s
iter=6 | energy=-16.263299 | time=1.8s
iter=7 | energy=-16.285971 | time=1.91s
iter=8 | energy=-16.304662 | time=2.14s
iter=9 | energy=-16.32161 | time=2.34s
iter=10 | energy=-16.336898 | time=2.59s


In [56]:
energies

array([ -4.3001611 , -15.09544705, -15.63950261, -15.97428654,
       -16.15438782, -16.22801447, -16.26329926, -16.28597055,
       -16.30466213, -16.32160951, -16.33689787])

In [57]:
MPS_MPS_overlap(MPS, MPS)

array(1.+0.j)

In [58]:
MPS_MPO_MPS_overlap(MPS, MPO, MPS)

array(-16.33689787+4.4408921e-16j)

In [59]:
np.linalg.norm(contract_MPS(MPS))

1.0000000000000002

In [60]:
np.linalg.norm(MPS_MPO_multiplication(MPS, MPO) / MPS_MPO_MPS_overlap(MPS, MPO, MPS) - contract_MPS(MPS))

0.20614643625956153