In [2]:
import numpy as np
import sys
import itertools as itertools
sys.path.append("..")
sys.path.append("../..")

import matplotlib.pyplot as plt
from python.Hubbard import Hubbard_model_with_filling, Double_occupancy, get_filling
from python.DMRG import DMRG
from python.Zippers import MPO_to_Hamiltonian, contract_MPS
from python.Canonical_Form import get_Neumann_entropy

In [66]:
n_sites = 100

hopping_t = 1.0
interaction_U = 1
chemical_potential = 0

Hamiltonian = Hubbard_model_with_filling(
    n_sites=n_sites, hopping_t=hopping_t,
    interaction_U=interaction_U, chemical_potential=chemical_potential,
)

MPO_transposed = [ham.transpose(2, 3, 0, 1) for ham in Hamiltonian]

In [ ]:
# """
# Get exact matrix (exponential barrier)
# """

# matrix = MPO_to_Hamiltonian(MPO_transposed)
# eigvals, _ = np.linalg.eigh(matrix)
# eigvals[:10]

array([-4.72818747, -4.40230342, -4.40230342, -4.10123611, -4.10123611,
       -3.93798172, -3.93798172, -3.93798172, -3.72818747, -3.66862141])

In [ ]:
# np.linalg.norm(matrix - matrix.conj().T)

0.0

In [67]:
NKeep = 20
NSweep = 10
Krylov_bases = 5 #* 5 is usually enough
Lanczos_cutoff = 1e-2
two_site = True
verbose = True

In [68]:
ground_energies, ground_times, ground_MPS = DMRG(
    Hamiltonian = Hamiltonian,
    NKeep = NKeep,
    NSweep = NSweep,
    Krylov_bases = Krylov_bases,
    Lanczos_cutoff = Lanczos_cutoff,
    iterative_diag = True,
    two_site = two_site,
    verbose = verbose,
)

# eigvals[0]

L=100 | NKeep=20 | NSweep=10 | iterative=True | two_site=True | Krylov_bases=5 | Lanczos_cutoff=0.01
iter=0 | energy=-105.67906 | time=0.0s
iter=1 | energy=-106.34163 | time=3.28s
iter=2 | energy=-106.40961 | time=5.73s
iter=3 | energy=-106.4175 | time=7.82s
iter=4 | energy=-106.41915 | time=10.4s
iter=5 | energy=-106.41944 | time=12.4s
iter=6 | energy=-106.41962 | time=14.9s
iter=7 | energy=-106.41974 | time=17.5s
iter=8 | energy=-106.41985 | time=19.6s
iter=9 | energy=-106.41988 | time=22.0s
iter=10 | energy=-106.4199 | time=24.1s


In [59]:
excited_energies, excited_times, excited_MPS = DMRG(
    Hamiltonian = Hamiltonian,
    NKeep = NKeep,
    NSweep = NSweep,
    Krylov_bases = Krylov_bases,
    Lanczos_cutoff = Lanczos_cutoff,
    iterative_diag = False,
    orthogonal_to_list_of_MPS=[ground_MPS],
    two_site = two_site,
    verbose = verbose,
)

eigvals[1]

L=5 | NKeep=20 | NSweep=10 | iterative=False | two_site=True | Krylov_bases=5 | Lanczos_cutoff=0.01
iter=0 | energy=1.4226157 | time=0.0s
iter=1 | energy=-4.4018439 | time=0.0676s
iter=2 | energy=-4.4022801 | time=0.107s
iter=3 | energy=-4.4022801 | time=0.126s
iter=4 | energy=-4.4022801 | time=0.149s
iter=5 | energy=-4.4022801 | time=0.191s
iter=6 | energy=-4.4022801 | time=0.232s
iter=7 | energy=-4.4022801 | time=0.264s
iter=8 | energy=-4.4022801 | time=0.303s
iter=9 | energy=-4.4022801 | time=0.337s
iter=10 | energy=-4.4022801 | time=0.372s


-4.402303420391809

In [60]:
get_Neumann_entropy(ground_MPS)

array([1.8589367 , 1.61241571, 1.61802789, 1.85550712])

In [61]:
get_Neumann_entropy(excited_MPS)

array([1.75692179, 1.47589815, 1.47684727, 1.756684  ])

In [62]:
get_filling(ground_MPS).sum()

4.000000059977084

In [63]:
get_filling(excited_MPS).sum()

(4.99990776892655-3.469446951953614e-17j)