In [3]:
import numpy as np
import sys
import itertools as itertools
sys.path.append("..")
sys.path.append("../..")

import matplotlib.pyplot as plt
from python.Dzyalonshinskii_Moriya_Ising import DM_Ising
from python.DMRG import DMRG
from python.Zippers import MPO_to_Hamiltonian, contract_MPS
from python.Canonical_Form import get_Neumann_entropy

In [3]:
n_sites = 5

J = 1.0
D = 2.0
magnetic_field = 0.0

Hamiltonian = DM_Ising(
    n_sites=n_sites, J=J, D=D, magnetic_field=magnetic_field
)

MPO_transposed = [ham.transpose(2, 3, 0, 1) for ham in Hamiltonian]

In [ ]:
"""
Get exact matrix (exponential barrier)
"""

matrix = MPO_to_Hamiltonian(MPO_transposed)
eigvals, _ = np.linalg.eigh(matrix)
eigvals[:10]

array([-3.25274574, -3.25274574, -2.03628705, -2.03628705, -1.66401564,
       -1.66401564, -1.12851004, -1.12851004, -1.07886104, -1.07886104])

In [5]:
np.linalg.norm(matrix - matrix.conj().T)

0.0

In [6]:
NKeep = 20
NSweep = 10
Krylov_bases = 5 #* 5 is usually enough
Lanczos_cutoff = 1e-2
iterative_diag = True
two_site = True
verbose = True

In [7]:
ground_energies, ground_times, ground_MPS = DMRG(
    Hamiltonian = Hamiltonian,
    NKeep = NKeep,
    NSweep = NSweep,
    Krylov_bases = Krylov_bases,
    Lanczos_cutoff = Lanczos_cutoff,
    iterative_diag = iterative_diag,
    two_site = two_site,
    verbose = verbose,
)

eigvals[0]

L=5 | NKeep=20 | NSweep=10 | iterative=True | two_site=True | Krylov_bases=5 | Lanczos_cutoff=0.01
iter=0 | energy=-3.1143643 | time=0.0s
iter=1 | energy=-3.2527455 | time=0.0154s
iter=2 | energy=-3.2527455 | time=0.0279s
iter=3 | energy=-3.2527455 | time=0.0397s
iter=4 | energy=-3.2527455 | time=0.0487s
iter=5 | energy=-3.2527455 | time=0.0582s
iter=6 | energy=-3.2527455 | time=0.0673s
iter=7 | energy=-3.2527455 | time=0.0765s
iter=8 | energy=-3.2527455 | time=0.087s
iter=9 | energy=-3.2527455 | time=0.0962s
iter=10 | energy=-3.2527455 | time=0.107s


-3.2527457389229784

In [8]:
excited_energies, excited_times, excited_MPS = DMRG(
    Hamiltonian = Hamiltonian,
    NKeep = NKeep,
    NSweep = NSweep,
    Krylov_bases = Krylov_bases,
    Lanczos_cutoff = Lanczos_cutoff,
    iterative_diag = False,
    orthogonal_to_list_of_MPS=[ground_MPS],
    two_site = two_site,
    verbose = verbose,
)

eigvals[1]

L=5 | NKeep=20 | NSweep=10 | iterative=False | two_site=True | Krylov_bases=5 | Lanczos_cutoff=0.01
iter=0 | energy=0.11294155 | time=0.0s
iter=1 | energy=-3.2527193 | time=0.0197s
iter=2 | energy=-3.2527193 | time=0.032s
iter=3 | energy=-3.2527193 | time=0.0446s
iter=4 | energy=-3.2527193 | time=0.0568s
iter=5 | energy=-3.2527193 | time=0.0694s
iter=6 | energy=-3.2527193 | time=0.0812s
iter=7 | energy=-3.2527193 | time=0.0933s
iter=8 | energy=-3.2527193 | time=0.105s
iter=9 | energy=-3.2527193 | time=0.118s
iter=10 | energy=-3.2527193 | time=0.131s


-3.252745738922972

In [9]:
get_Neumann_entropy(ground_MPS)

array([0.86963479, 0.68087358, 0.68053553, 0.86945157])

In [10]:
get_Neumann_entropy(excited_MPS)

array([0.86969975, 0.67960124, 0.67989058, 0.869272  ])